// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxyunvvkchhhzgspiflq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54eXVudnZrY2hoaHpnc3BpZmxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMjE0NjcsImV4cCI6MjA3Mzc5NzQ2N30.95hjL9Z9qeQWV8WKhoZ2MplAeqd_LqmkLoTXQHCnYpM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});